# Generated by Django 4.2.8 on 2026-02-04 08:41

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnrollmentRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('experience', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='beginner', max_length=20)),
                ('course_title', models.CharField(max_length=255)),
                ('course_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('course_duration', models.CharField(max_length=50)),
                ('course_level', models.CharField(max_length=20)),
                ('enrollment_date', models.DateTimeField(auto_now_add=True)),
                ('is_paid', models.BooleanField(default=False)),
                ('payment_id', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'ordering': ['-enrollment_date'],
                'indexes': [models.Index(fields=['email'], name='courses_enr_email_6bbb05_idx'), models.Index(fields=['is_paid'], name='courses_enr_is_paid_cf21bd_idx')],
            },
        ),
    ]
