# Generated by Django 4.2.8 on 2026-02-05 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_enrollmentrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollmentrequest',
            name='course_level',
            field=models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='beginner', max_length=20),
        ),
    ]
